# Generated by Django 5.2 on 2025-05-04 21:57

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkUsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the vacancy",
                        max_length=255,
                        verbose_name="Name of the vacancy",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the vacancy",
                        verbose_name="Description of the vacancy",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the vacancy",
                        max_length=255,
                        verbose_name="Location of the vacancy",
                    ),
                ),
                (
                    "salary",
                    models.FloatField(
                        help_text="Salary of the vacancy",
                        verbose_name="Salary of the vacancy",
                    ),
                ),
                (
                    "requirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        help_text="Requirements of the vacancy",
                        size=None,
                        verbose_name="Requirements of the vacancy",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that offers the vacancy",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="people.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CandidateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the candidate",
                        max_length=255,
                        verbose_name="Name of the candidate",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the candidate",
                        max_length=254,
                        verbose_name="Email of the candidate",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone of the candidate",
                        max_length=255,
                        verbose_name="Phone of the candidate",
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Resume of the candidate",
                        null=True,
                        upload_to="resumes/",
                        verbose_name="Resume of the candidate",
                    ),
                ),
                (
                    "cvv",
                    models.FileField(
                        help_text="CVV of the candidate",
                        upload_to="cvv/",
                        verbose_name="CVV of the candidate",
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        default=0,
                        help_text="Stars of the candidate",
                        verbose_name="Stars of the candidate",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="Vacancy that the candidate applied for",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="work_us.workusmodel",
                        verbose_name="Vacancy",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
