# Generated by Django 5.2 on 2025-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_us", "0002_candidatemodel_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatemodel",
            name="resume",
            field=models.TextField(
                blank=True,
                help_text="Resume of the candidate",
                null=True,
                verbose_name="Resume of the candidate",
            ),
        ),
    ]
