# Generated by Django 5.2.1 on 2025-05-10 19:30

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_us', '0003_alter_candidatemodel_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemodel',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Candidatos'},
        ),
        migrations.AlterModelOptions(
            name='workusmodel',
            options={'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
        migrations.AddField(
            model_name='candidatemodel',
            name='number_id',
            field=models.CharField(default=1001560611, help_text='Number ID of the candidate', max_length=255, verbose_name='Number ID of the candidate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BackgroundPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('organization', models.CharField(choices=[('Attorney', 'Procuraduria General de la Nación')], help_text='Organization of the background', max_length=255, verbose_name='Organization of the background')),
                ('query', models.TextField(help_text='Description of the background', verbose_name='Description of the background')),
                ('candidate', models.ForeignKey(help_text='Candidate that has the background', on_delete=django.db.models.deletion.DO_NOTHING, to='work_us.candidatemodel', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antedecentes',
            },
        ),
    ]
