# Generated by Django 5.2.1 on 2025-05-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_us', '0004_alter_candidatemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='vacancy',
            field=models.ForeignKey(help_text='Vacancy that the candidate applied for', on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidates', to='work_us.workusmodel', verbose_name='Vacancy'),
        ),
    ]
