# Generated by Django 5.2 on 2025-05-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_personcompany_salary'),
        ('work_us', '0004_alter_candidatemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workusmodel',
            name='company',
            field=models.ForeignKey(help_text='Company that offers the vacancy', on_delete=django.db.models.deletion.CASCADE, to='people.company', verbose_name='Company'),
        ),
    ]
