# Generated by Django 5.2 on 2025-05-11 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_us', '0005_alter_candidatemodel_vacancy'),
        ('work_us', '0005_alter_workusmodel_company'),
    ]

    operations = [
    ]
