# Generated by Django 5.2.1 on 2025-05-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_us', '0007_alter_backgroundpersonmodel_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the candidate', max_length=254, null=True, verbose_name='Email of the candidate'),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone of the candidate', max_length=255, null=True, verbose_name='Phone of the candidate'),
        ),
    ]
