services:
  database:
    image: postgres:15-bullseye
    env_file:
      - .env
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    command: gunicorn humanos.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database

volumes:
  postgres_data:
