services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:${POSTGRES_PORT:-5432}"

  backend:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8000:${BACKEND_PORT:-8000}"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: