services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5437:5432"

  backend:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: