[project]
name = "humanos"
version = "0.1.0"
description = "HumanOS Project"
requires-python = ">=3.13.1"
dependencies = [
    "asgiref==3.8.1",
    "django==5.2",
    "djangorestframework==3.16.0",
    "gunicorn==21.2.0",
    "psycopg2-binary==2.9.10",
    "sqlparse==0.5.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
