# Generated by Django 5.2 on 2025-05-08 03:39

import doc_gen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_gen', '0002_userrequesteddoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesteddoc',
            name='file',
            field=models.FileField(upload_to=doc_gen.models.UserRequestedDoc.upload_to),
        ),
    ]
