# Generated by Django 5.2 on 2025-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_gen", "0003_alter_userrequesteddoc_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docxtemplate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
