# Generated by Django 5.2 on 2025-05-08 03:39

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Enter the start date", verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Enter the end date", verbose_name="End Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Select the status",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Select the person",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
