# Generated by Django 5.2 on 2025-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_vacationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationrequest",
            name="days",
            field=models.IntegerField(
                blank=True,
                help_text="Enter the number of days",
                null=True,
                verbose_name="Days",
            ),
        ),
    ]
