# Generated by Django 5.2 on 2025-05-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_personcompany_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="personcompany",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Enter the salary",
                max_digits=10,
                null=True,
                verbose_name="Salary",
            ),
        ),
    ]
